// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrs5sAN3qmk9c8eR5o5JPrZwwek6qMZUQ',
    appId: '1:538092630030:web:e29d5dbdb2cd9056e8cc5f',
    messagingSenderId: '538092630030',
    projectId: 'learn-crud-auth',
    authDomain: 'learn-crud-auth.firebaseapp.com',
    databaseURL: 'https://learn-crud-auth-default-rtdb.firebaseio.com',
    storageBucket: 'learn-crud-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzFiFNCMvUE9pTNqV79oWn651MKhmziLE',
    appId: '1:538092630030:android:cb65b5edb8882abee8cc5f',
    messagingSenderId: '538092630030',
    projectId: 'learn-crud-auth',
    databaseURL: 'https://learn-crud-auth-default-rtdb.firebaseio.com',
    storageBucket: 'learn-crud-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvTbl0vqfdi--TqSP3ZUMyzZIZr-gkIvs',
    appId: '1:538092630030:ios:88ba5f044a4f9d73e8cc5f',
    messagingSenderId: '538092630030',
    projectId: 'learn-crud-auth',
    databaseURL: 'https://learn-crud-auth-default-rtdb.firebaseio.com',
    storageBucket: 'learn-crud-auth.appspot.com',
    androidClientId: '538092630030-el5qd8de5alb59f67hj104fm16hruq5r.apps.googleusercontent.com',
    iosClientId: '538092630030-oqsp0jfrq0v0gtebbghaauaiv1d21cg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreAuthRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvTbl0vqfdi--TqSP3ZUMyzZIZr-gkIvs',
    appId: '1:538092630030:ios:88ba5f044a4f9d73e8cc5f',
    messagingSenderId: '538092630030',
    projectId: 'learn-crud-auth',
    databaseURL: 'https://learn-crud-auth-default-rtdb.firebaseio.com',
    storageBucket: 'learn-crud-auth.appspot.com',
    androidClientId: '538092630030-el5qd8de5alb59f67hj104fm16hruq5r.apps.googleusercontent.com',
    iosClientId: '538092630030-oqsp0jfrq0v0gtebbghaauaiv1d21cg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreAuthRiverpod',
  );
}
